repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        name: Lint code with Ruff
        args: [ --fix ]
        files: ^backend/
      - id: ruff-format
        name: Format code with Ruff
        files: ^backend/

  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm --prefix frontend exec -- eslint --fix
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx|vue)$

      - id: frontend-prettier
        name: ✨ Prettier (Frontend)
        entry: npm --prefix frontend exec -- prettier --write
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx|css|scss|html|json|vue)$

      - id: mypy
        name: Type check with Mypy
        entry: uv run mypy --config-file backend/pyproject.toml
        language: system
        types: [python]
        files: ^backend/app/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
