name: bndsphere

services:
  postgres:
    image: bndsphere-postgres
    build:
      context: ./infra
      dockerfile: Dockerfile.Postgres

  backend:
    image: bndsphere-backend
    build:
      context: ./backend
      network: host
      target: prod

  backend-dev:
    image: bndsphere-backend:dev
    build:
      context: ./backend
      network: host
      target: dev

  caddy:
    image: bndsphere-caddy
    build:
      context: .
      dockerfile: infra/Dockerfile.Caddy
      network: host
      target: prod

