[project]
name = "bndsphere"
version = "0.1.0"
description = "bnds club manage platform"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "fastapi-pagination>=0.15.12",
    "fastapi[standard]>=0.135.1",
    "passlib[argon2]>=1.7.4",
    "psycopg[binary]>=3.3.3",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pyjwt>=2.12.1",
    "sqlalchemy>=2.0.48",
    "uvicorn[standard]>=0.42.0",
]

[dependency-groups]
dev = []

[tool.mypy]
strict = true

[tool.ruff.lint.pylint]
max-args = 8

[tool.ruff.lint]
select =["ALL"]
extend-ignore = ['EM102', 'EM101', 'TRY003', 'D107', 'D102', 'D103', 'TC001', 'D101', 'D100', 'D104', 'TC002', 'TC003', 'D205']

[tool.ruff]
extend-exclude = ["**/migrations"]
