FROM caddy:2-alpine AS base
RUN addgroup -S caddygroup && adduser -S -G caddygroup caddyuser
RUN setcap -r /usr/bin/caddy || true
RUN mkdir -p /data/caddy /etc/caddy /srv && \
    chown -R caddyuser:caddygroup /data /etc/caddy /srv
USER caddyuser
EXPOSE 8080
HEALTHCHECK --interval=10s --timeout=5s --retries=5 \
    CMD wget -q --spider http://localhost:8080/ || exit 1

FROM base AS dev

FROM node:24-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY ./frontend ./
RUN npm run build

FROM base AS prod
ARG APP_VERSION=dev
ENV APP_VERSION=${APP_VERSION}

COPY --from=builder --chown=caddyuser:caddygroup /app/dist /srv
COPY --chown=caddyuser:caddygroup ./infra/Caddyfile /etc/caddy/Caddyfile
