FROM node:24-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY ./frontend ./

RUN npm run build

FROM caddy:2-alpine

RUN addgroup -S caddygroup && adduser -S -G caddygroup caddyuser
RUN mkdir -p /config/caddy /data/caddy /etc/caddy /srv && \
    chown -R caddyuser:caddygroup /config /data /etc/caddy /srv
COPY --from=builder --chown=caddyuser:caddygroup /app/dist /srv
COPY --chown=caddyuser:caddygroup ./infra/Caddyfile /etc/caddy/Caddyfile
USER caddyuser

EXPOSE 8080
