// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
  CreateApiV1AdminGeneralActivitiesPostData,
  CreateApiV1AdminGeneralActivitiesPostErrors,
  CreateApiV1AdminGeneralActivitiesPostResponses,
  CreateClubActivityApiV1ClubsClubIdActivitiesPostData,
  CreateClubActivityApiV1ClubsClubIdActivitiesPostErrors,
  CreateClubActivityApiV1ClubsClubIdActivitiesPostResponses,
  CreateClubApiV1ClubsPostData,
  CreateClubApiV1ClubsPostErrors,
  CreateClubApiV1ClubsPostResponses,
  CreateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPostData,
  CreateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPostErrors,
  CreateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPostResponses,
  CreateTermApiV1AdminAcademicTermsPostData,
  CreateTermApiV1AdminAcademicTermsPostErrors,
  CreateTermApiV1AdminAcademicTermsPostResponses,
  DeleteApiV1AdminGeneralActivitiesActivityIdDeleteData,
  DeleteApiV1AdminGeneralActivitiesActivityIdDeleteErrors,
  DeleteApiV1AdminGeneralActivitiesActivityIdDeleteResponses,
  DeleteTermApiV1AdminAcademicTermsTermIdDeleteData,
  DeleteTermApiV1AdminAcademicTermsTermIdDeleteErrors,
  DeleteTermApiV1AdminAcademicTermsTermIdDeleteResponses,
  GetApiV1GeneralActivitiesActivityIdGetData,
  GetApiV1GeneralActivitiesActivityIdGetErrors,
  GetApiV1GeneralActivitiesActivityIdGetResponses,
  GetClubActivitiesApiV1ClubsClubIdActivitiesGetData,
  GetClubActivitiesApiV1ClubsClubIdActivitiesGetErrors,
  GetClubActivitiesApiV1ClubsClubIdActivitiesGetResponses,
  GetClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesGetData,
  GetClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesGetErrors,
  GetClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesGetResponses,
  GetClubInfoApiV1ClubsClubIdGetData,
  GetClubInfoApiV1ClubsClubIdGetErrors,
  GetClubInfoApiV1ClubsClubIdGetResponses,
  GetCurrentUserInfoApiV1UsersMeGetData,
  GetCurrentUserInfoApiV1UsersMeGetErrors,
  GetCurrentUserInfoApiV1UsersMeGetResponses,
  GetTermApiV1AdminAcademicTermsTermIdGetData,
  GetTermApiV1AdminAcademicTermsTermIdGetErrors,
  GetTermApiV1AdminAcademicTermsTermIdGetResponses,
  GetUserProfileApiV1UsersUserIdGetData,
  GetUserProfileApiV1UsersUserIdGetErrors,
  GetUserProfileApiV1UsersUserIdGetResponses,
  JoinClubApiV1ClubsClubIdMembersPostData,
  JoinClubApiV1ClubsClubIdMembersPostErrors,
  JoinClubApiV1ClubsClubIdMembersPostResponses,
  LeaveClubApiV1ClubsClubIdMembersMeDeleteData,
  LeaveClubApiV1ClubsClubIdMembersMeDeleteErrors,
  LeaveClubApiV1ClubsClubIdMembersMeDeleteResponses,
  ListActivitiesApiV1GeneralActivitiesGetData,
  ListActivitiesApiV1GeneralActivitiesGetErrors,
  ListActivitiesApiV1GeneralActivitiesGetResponses,
  ListClubsApiV1ClubsGetData,
  ListClubsApiV1ClubsGetErrors,
  ListClubsApiV1ClubsGetResponses,
  ListTermsApiV1AdminAcademicTermsGetData,
  ListTermsApiV1AdminAcademicTermsGetErrors,
  ListTermsApiV1AdminAcademicTermsGetResponses,
  LoginApiV1AuthLoginPostData,
  LoginApiV1AuthLoginPostErrors,
  LoginApiV1AuthLoginPostResponses,
  RegisterApiV1AuthRegisterPostData,
  RegisterApiV1AuthRegisterPostErrors,
  RegisterApiV1AuthRegisterPostResponses,
  SetCurrentTermApiV1AdminAcademicTermsTermIdSetCurrentPostData,
  SetCurrentTermApiV1AdminAcademicTermsTermIdSetCurrentPostErrors,
  SetCurrentTermApiV1AdminAcademicTermsTermIdSetCurrentPostResponses,
  UpdateApiV1AdminGeneralActivitiesActivityIdPatchData,
  UpdateApiV1AdminGeneralActivitiesActivityIdPatchErrors,
  UpdateApiV1AdminGeneralActivitiesActivityIdPatchResponses,
  UpdateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPatchData,
  UpdateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPatchErrors,
  UpdateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPatchResponses,
  UpdateClubInfoApiV1ClubsClubIdPatchData,
  UpdateClubInfoApiV1ClubsClubIdPatchErrors,
  UpdateClubInfoApiV1ClubsClubIdPatchResponses,
  UpdateTermApiV1AdminAcademicTermsTermIdPatchData,
  UpdateTermApiV1AdminAcademicTermsTermIdPatchErrors,
  UpdateTermApiV1AdminAcademicTermsTermIdPatchResponses,
  UpdateUserProfileApiV1UsersMePatchData,
  UpdateUserProfileApiV1UsersMePatchErrors,
  UpdateUserProfileApiV1UsersMePatchResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Current User Info
 *
 * Get public profile of current user.
 */
export const getCurrentUserInfoApiV1UsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserInfoApiV1UsersMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCurrentUserInfoApiV1UsersMeGetResponses,
    GetCurrentUserInfoApiV1UsersMeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
  });

/**
 * Update User Profile
 *
 * Modify user profile of current user.
 *
 * Note that username cannot be changed, and email must be unique.
 */
export const updateUserProfileApiV1UsersMePatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserProfileApiV1UsersMePatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateUserProfileApiV1UsersMePatchResponses,
    UpdateUserProfileApiV1UsersMePatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get User Profile
 *
 * Get public profile of a user by user id.
 */
export const getUserProfileApiV1UsersUserIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetUserProfileApiV1UsersUserIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserProfileApiV1UsersUserIdGetResponses,
    GetUserProfileApiV1UsersUserIdGetErrors,
    ThrowOnError
  >({ url: '/api/v1/users/{user_id}', ...options });

/**
 * Register
 *
 * Register a new user. Username must be unique.
 */
export const registerApiV1AuthRegisterPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterApiV1AuthRegisterPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterApiV1AuthRegisterPostResponses,
    RegisterApiV1AuthRegisterPostErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Login
 *
 * Login with username and password. Returns a JWT token if successful.
 *
 * Note that all optional fields in the form data are ignored.
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginApiV1AuthLoginPostResponses,
    LoginApiV1AuthLoginPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });

/**
 * Get Club Info
 *
 * Get information of a club by club id.
 */
export const getClubInfoApiV1ClubsClubIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetClubInfoApiV1ClubsClubIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetClubInfoApiV1ClubsClubIdGetResponses,
    GetClubInfoApiV1ClubsClubIdGetErrors,
    ThrowOnError
  >({ url: '/api/v1/clubs/{club_id}', ...options });

/**
 * Update Club Info
 *
 * Get information of a club by club id.
 */
export const updateClubInfoApiV1ClubsClubIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateClubInfoApiV1ClubsClubIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateClubInfoApiV1ClubsClubIdPatchResponses,
    UpdateClubInfoApiV1ClubsClubIdPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clubs/{club_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Clubs
 *
 * Search Clubs.
 */
export const listClubsApiV1ClubsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListClubsApiV1ClubsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListClubsApiV1ClubsGetResponses,
    ListClubsApiV1ClubsGetErrors,
    ThrowOnError
  >({ url: '/api/v1/clubs/', ...options });

/**
 * Create Club
 *
 * Create a new club. Club name must be unique among non-archived clubs.
 */
export const createClubApiV1ClubsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateClubApiV1ClubsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateClubApiV1ClubsPostResponses,
    CreateClubApiV1ClubsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clubs/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Join Club
 *
 * Join a club.
 */
export const joinClubApiV1ClubsClubIdMembersPost = <ThrowOnError extends boolean = false>(
  options: Options<JoinClubApiV1ClubsClubIdMembersPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    JoinClubApiV1ClubsClubIdMembersPostResponses,
    JoinClubApiV1ClubsClubIdMembersPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clubs/{club_id}/members',
    ...options,
  });

/**
 * Leave Club
 *
 * Leave a club.
 */
export const leaveClubApiV1ClubsClubIdMembersMeDelete = <ThrowOnError extends boolean = false>(
  options: Options<LeaveClubApiV1ClubsClubIdMembersMeDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    LeaveClubApiV1ClubsClubIdMembersMeDeleteResponses,
    LeaveClubApiV1ClubsClubIdMembersMeDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clubs/{club_id}/members/me',
    ...options,
  });

/**
 * Get Club Activities
 */
export const getClubActivitiesApiV1ClubsClubIdActivitiesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetClubActivitiesApiV1ClubsClubIdActivitiesGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetClubActivitiesApiV1ClubsClubIdActivitiesGetResponses,
    GetClubActivitiesApiV1ClubsClubIdActivitiesGetErrors,
    ThrowOnError
  >({ url: '/api/v1/clubs/{club_id}/activities/', ...options });

/**
 * Create Club Activity
 */
export const createClubActivityApiV1ClubsClubIdActivitiesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateClubActivityApiV1ClubsClubIdActivitiesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateClubActivityApiV1ClubsClubIdActivitiesPostResponses,
    CreateClubActivityApiV1ClubsClubIdActivitiesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clubs/{club_id}/activities/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Terms
 */
export const listTermsApiV1AdminAcademicTermsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListTermsApiV1AdminAcademicTermsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTermsApiV1AdminAcademicTermsGetResponses,
    ListTermsApiV1AdminAcademicTermsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/academic-terms/',
    ...options,
  });

/**
 * Create Term
 */
export const createTermApiV1AdminAcademicTermsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTermApiV1AdminAcademicTermsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateTermApiV1AdminAcademicTermsPostResponses,
    CreateTermApiV1AdminAcademicTermsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/academic-terms/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Term
 */
export const deleteTermApiV1AdminAcademicTermsTermIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTermApiV1AdminAcademicTermsTermIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTermApiV1AdminAcademicTermsTermIdDeleteResponses,
    DeleteTermApiV1AdminAcademicTermsTermIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/academic-terms/{term_id}',
    ...options,
  });

/**
 * Get Term
 */
export const getTermApiV1AdminAcademicTermsTermIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTermApiV1AdminAcademicTermsTermIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTermApiV1AdminAcademicTermsTermIdGetResponses,
    GetTermApiV1AdminAcademicTermsTermIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/academic-terms/{term_id}',
    ...options,
  });

/**
 * Update Term
 */
export const updateTermApiV1AdminAcademicTermsTermIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTermApiV1AdminAcademicTermsTermIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateTermApiV1AdminAcademicTermsTermIdPatchResponses,
    UpdateTermApiV1AdminAcademicTermsTermIdPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/academic-terms/{term_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Set Current Term
 */
export const setCurrentTermApiV1AdminAcademicTermsTermIdSetCurrentPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SetCurrentTermApiV1AdminAcademicTermsTermIdSetCurrentPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SetCurrentTermApiV1AdminAcademicTermsTermIdSetCurrentPostResponses,
    SetCurrentTermApiV1AdminAcademicTermsTermIdSetCurrentPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/academic-terms/{term_id}/set-current',
    ...options,
  });

/**
 * Create
 */
export const createApiV1AdminGeneralActivitiesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateApiV1AdminGeneralActivitiesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateApiV1AdminGeneralActivitiesPostResponses,
    CreateApiV1AdminGeneralActivitiesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/general-activities/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete
 */
export const deleteApiV1AdminGeneralActivitiesActivityIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiV1AdminGeneralActivitiesActivityIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiV1AdminGeneralActivitiesActivityIdDeleteResponses,
    DeleteApiV1AdminGeneralActivitiesActivityIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/general-activities/{activity_id}',
    ...options,
  });

/**
 * Update
 */
export const updateApiV1AdminGeneralActivitiesActivityIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateApiV1AdminGeneralActivitiesActivityIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateApiV1AdminGeneralActivitiesActivityIdPatchResponses,
    UpdateApiV1AdminGeneralActivitiesActivityIdPatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/general-activities/{activity_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get
 */
export const getApiV1GeneralActivitiesActivityIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1GeneralActivitiesActivityIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1GeneralActivitiesActivityIdGetResponses,
    GetApiV1GeneralActivitiesActivityIdGetErrors,
    ThrowOnError
  >({ url: '/api/v1/general-activities/{activity_id}', ...options });

/**
 * List Activities
 */
export const listActivitiesApiV1GeneralActivitiesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListActivitiesApiV1GeneralActivitiesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListActivitiesApiV1GeneralActivitiesGetResponses,
    ListActivitiesApiV1GeneralActivitiesGetErrors,
    ThrowOnError
  >({ url: '/api/v1/general-activities/', ...options });

/**
 * Get Club General Activities
 */
export const getClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesGetResponses,
    GetClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesGetErrors,
    ThrowOnError
  >({ url: '/api/v1/clubs/{club_id}/general-activities/', ...options });

/**
 * Update Club General Activities
 */
export const updateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPatchResponses,
    UpdateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPatchErrors,
    ThrowOnError
  >({
    url: '/api/v1/clubs/{club_id}/general-activities/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Club General Activities
 */
export const createClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    CreateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPostResponses,
    CreateClubGeneralActivitiesApiV1ClubsClubIdGeneralActivitiesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clubs/{club_id}/general-activities/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
