// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://src` | (string & {});
};

/**
 * AcademicTermCreate
 */
export type AcademicTermCreate = {
  /**
   * Term Name
   */
  term_name?: string | null;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * End Date
   */
  end_date: string;
};

/**
 * AcademicTermInfo
 */
export type AcademicTermInfo = {
  /**
   * Term Name
   */
  term_name: string;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * End Date
   */
  end_date: string;
};

/**
 * AcademicTermUpdate
 */
export type AcademicTermUpdate = {
  /**
   * Term Name
   */
  term_name?: string | null;
  /**
   * Start Date
   */
  start_date?: string | null;
  /**
   * End Date
   */
  end_date?: string | null;
};

/**
 * ActivityCreate
 */
export type ActivityCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Location
   */
  location: string;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * End Time
   */
  end_time: string;
};

/**
 * ActivityInfo
 */
export type ActivityInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Location
   */
  location: string;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * End Time
   */
  end_time: string;
  /**
   * Club Id
   */
  club_id: number;
  /**
   * Picture Urls
   */
  picture_urls: Array<string>;
};

/**
 * AuditStatusEnum
 */
export type AuditStatusEnum = 'pending' | 'approved' | 'rejected';

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * ClubCategoryEnum
 */
export type ClubCategoryEnum =
  | 'sports'
  | 'humanity'
  | 'arts'
  | 'science'
  | 'charity'
  | 'business'
  | 'campus'
  | 'other';

/**
 * ClubCreate
 */
export type ClubCreate = {
  /**
   * Name
   */
  name: string;
  category: ClubCategoryEnum;
  /**
   * Summary
   */
  summary: string;
  /**
   * Description
   */
  description: string;
  /**
   * Logo Uri
   */
  logo_uri?: string | null;
};

/**
 * ClubGeneralActivityInfo
 */
export type ClubGeneralActivityInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Proof Files
   */
  proof_files: string | null;
  /**
   * Created At
   */
  created_at: string;
  audit_status: AuditStatusEnum;
  /**
   * Final Score
   */
  final_score: number;
  participation_type: ParticipationTypeEnum;
  /**
   * Met Conditions
   */
  met_conditions: Array<RecordConditionDetail>;
  /**
   * Club Id
   */
  club_id: number;
  /**
   * Activity Id
   */
  activity_id: number;
};

/**
 * ClubInfo
 */
export type ClubInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  category: ClubCategoryEnum;
  /**
   * Summary
   */
  summary: string;
  /**
   * Description
   */
  description: string;
  /**
   * Logo Uri
   */
  logo_uri?: string | null;
  /**
   * Created At
   */
  created_at: string;
  status: ClubStatusEnum;
  star_level: ClubStarLevelEnum;
  /**
   * Members
   */
  members: Array<ClubMemberInfo>;
  /**
   * Activities
   */
  activities: Array<ActivityInfo>;
};

/**
 * ClubMemberInfo
 */
export type ClubMemberInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Club Id
   */
  club_id: number;
  membership: ClubMembershipEnum;
};

/**
 * ClubMembershipEnum
 */
export type ClubMembershipEnum = 'pending' | 'member' | 'president' | 'vice president' | 'left';

/**
 * ClubStarLevelEnum
 */
export type ClubStarLevelEnum =
  | 'none'
  | 'one_star'
  | 'two_star'
  | 'three_star'
  | 'four_star'
  | 'five_star'
  | 'honorary';

/**
 * ClubStatusEnum
 */
export type ClubStatusEnum = 'unreviewed' | 'normal' | 'archived';

/**
 * ClubUpdate
 */
export type ClubUpdate = {
  /**
   * Summary
   */
  summary: string;
  /**
   * Description
   */
  description: string;
  /**
   * Logo Uri
   */
  logo_uri?: string | null;
};

/**
 * GeneralActivityCreate
 */
export type GeneralActivityCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  level: GeneralActivityLevelEnum;
};

/**
 * GeneralActivityInfo
 */
export type GeneralActivityInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  level: GeneralActivityLevelEnum;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Club Records
   */
  club_records: Array<ClubGeneralActivityInfo>;
};

/**
 * GeneralActivityLevelEnum
 */
export type GeneralActivityLevelEnum = 'school' | 'large' | 'sua';

/**
 * GeneralActivityUpdate
 */
export type GeneralActivityUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  level?: GeneralActivityLevelEnum | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * PageResponse[ActivityInfo]
 */
export type PageResponseActivityInfo = {
  /**
   * Total
   */
  total: number;
  /**
   * Items
   */
  items: Array<ActivityInfo>;
};

/**
 * PageResponse[ClubInfo]
 */
export type PageResponseClubInfo = {
  /**
   * Total
   */
  total: number;
  /**
   * Items
   */
  items: Array<ClubInfo>;
};

/**
 * ParticipationTypeEnum
 */
export type ParticipationTypeEnum = 'participate_only' | 'organize';

/**
 * RecordConditionDetail
 */
export type RecordConditionDetail = {
  /**
   * Is Met
   */
  is_met: boolean;
  /**
   * Record Id
   */
  record_id: number;
  /**
   * Condition Id
   */
  condition_id: number;
};

/**
 * RoleEnum
 */
export type RoleEnum = 'ban' | 'user' | 'union of associations' | 'admin' | 'dev';

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserInfo
 */
export type UserInfo = {
  /**
   * Id
   */
  id: number;
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email: string | null;
  /**
   * Avatar Uri
   */
  avatar_uri: string | null;
  /**
   * Description
   */
  description: string;
  role: RoleEnum;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Avatar Uri
   */
  avatar_uri?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetCurrentUserInfoApiV1UsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type GetCurrentUserInfoApiV1UsersMeGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
};

export type GetCurrentUserInfoApiV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserInfo;
};

export type GetCurrentUserInfoApiV1UsersMeGetResponse =
  GetCurrentUserInfoApiV1UsersMeGetResponses[keyof GetCurrentUserInfoApiV1UsersMeGetResponses];

export type UpdateUserProfileApiV1UsersMePatchData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type UpdateUserProfileApiV1UsersMePatchErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Email already exists
   */
  409: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserProfileApiV1UsersMePatchError =
  UpdateUserProfileApiV1UsersMePatchErrors[keyof UpdateUserProfileApiV1UsersMePatchErrors];

export type UpdateUserProfileApiV1UsersMePatchResponses = {
  /**
   * Successful Response
   */
  200: UserInfo;
};

export type UpdateUserProfileApiV1UsersMePatchResponse =
  UpdateUserProfileApiV1UsersMePatchResponses[keyof UpdateUserProfileApiV1UsersMePatchResponses];

export type GetUserProfileApiV1UsersUserIdGetData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/api/v1/users/{user_id}';
};

export type GetUserProfileApiV1UsersUserIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserProfileApiV1UsersUserIdGetError =
  GetUserProfileApiV1UsersUserIdGetErrors[keyof GetUserProfileApiV1UsersUserIdGetErrors];

export type GetUserProfileApiV1UsersUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserInfo;
};

export type GetUserProfileApiV1UsersUserIdGetResponse =
  GetUserProfileApiV1UsersUserIdGetResponses[keyof GetUserProfileApiV1UsersUserIdGetResponses];

export type RegisterApiV1AuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
  /**
   * Username already exists
   */
  400: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError =
  RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserInfo;
};

export type RegisterApiV1AuthRegisterPostResponse =
  RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type LoginApiV1AuthLoginPostData = {
  body: BodyLoginApiV1AuthLoginPost;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
  /**
   * Incorrect username or password
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError =
  LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginApiV1AuthLoginPostResponse =
  LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type GetClubInfoApiV1ClubsClubIdGetData = {
  body?: never;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/api/v1/clubs/{club_id}';
};

export type GetClubInfoApiV1ClubsClubIdGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetClubInfoApiV1ClubsClubIdGetError =
  GetClubInfoApiV1ClubsClubIdGetErrors[keyof GetClubInfoApiV1ClubsClubIdGetErrors];

export type GetClubInfoApiV1ClubsClubIdGetResponses = {
  /**
   * Successful Response
   */
  200: ClubInfo;
};

export type GetClubInfoApiV1ClubsClubIdGetResponse =
  GetClubInfoApiV1ClubsClubIdGetResponses[keyof GetClubInfoApiV1ClubsClubIdGetResponses];

export type UpdateClubInfoApiV1ClubsClubIdPatchData = {
  body: ClubUpdate;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/api/v1/clubs/{club_id}';
};

export type UpdateClubInfoApiV1ClubsClubIdPatchErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateClubInfoApiV1ClubsClubIdPatchError =
  UpdateClubInfoApiV1ClubsClubIdPatchErrors[keyof UpdateClubInfoApiV1ClubsClubIdPatchErrors];

export type UpdateClubInfoApiV1ClubsClubIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ClubInfo;
};

export type UpdateClubInfoApiV1ClubsClubIdPatchResponse =
  UpdateClubInfoApiV1ClubsClubIdPatchResponses[keyof UpdateClubInfoApiV1ClubsClubIdPatchResponses];

export type ListClubsApiV1ClubsGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Search
     */
    search?: string | null;
    /**
     * Category
     */
    category?: ClubCategoryEnum | null;
  };
  url: '/api/v1/clubs/';
};

export type ListClubsApiV1ClubsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListClubsApiV1ClubsGetError =
  ListClubsApiV1ClubsGetErrors[keyof ListClubsApiV1ClubsGetErrors];

export type ListClubsApiV1ClubsGetResponses = {
  /**
   * Successful Response
   */
  200: PageResponseClubInfo;
};

export type ListClubsApiV1ClubsGetResponse =
  ListClubsApiV1ClubsGetResponses[keyof ListClubsApiV1ClubsGetResponses];

export type CreateClubApiV1ClubsPostData = {
  body: ClubCreate;
  path?: never;
  query?: never;
  url: '/api/v1/clubs/';
};

export type CreateClubApiV1ClubsPostErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Club with the same name already exists
   */
  409: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateClubApiV1ClubsPostError =
  CreateClubApiV1ClubsPostErrors[keyof CreateClubApiV1ClubsPostErrors];

export type CreateClubApiV1ClubsPostResponses = {
  /**
   * Successful Response
   */
  201: ClubInfo;
};

export type CreateClubApiV1ClubsPostResponse =
  CreateClubApiV1ClubsPostResponses[keyof CreateClubApiV1ClubsPostResponses];

export type JoinClubApiV1ClubsClubIdMembersPostData = {
  body?: never;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/api/v1/clubs/{club_id}/members';
};

export type JoinClubApiV1ClubsClubIdMembersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type JoinClubApiV1ClubsClubIdMembersPostError =
  JoinClubApiV1ClubsClubIdMembersPostErrors[keyof JoinClubApiV1ClubsClubIdMembersPostErrors];

export type JoinClubApiV1ClubsClubIdMembersPostResponses = {
  /**
   * Successful Response
   */
  201: ClubMemberInfo;
};

export type JoinClubApiV1ClubsClubIdMembersPostResponse =
  JoinClubApiV1ClubsClubIdMembersPostResponses[keyof JoinClubApiV1ClubsClubIdMembersPostResponses];

export type LeaveClubApiV1ClubsClubIdMembersMeDeleteData = {
  body?: never;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/api/v1/clubs/{club_id}/members/me';
};

export type LeaveClubApiV1ClubsClubIdMembersMeDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LeaveClubApiV1ClubsClubIdMembersMeDeleteError =
  LeaveClubApiV1ClubsClubIdMembersMeDeleteErrors[keyof LeaveClubApiV1ClubsClubIdMembersMeDeleteErrors];

export type LeaveClubApiV1ClubsClubIdMembersMeDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type LeaveClubApiV1ClubsClubIdMembersMeDeleteResponse =
  LeaveClubApiV1ClubsClubIdMembersMeDeleteResponses[keyof LeaveClubApiV1ClubsClubIdMembersMeDeleteResponses];

export type GetClubActivitiesApiV1ClubsClubIdActivitiesGetData = {
  body?: never;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query: {
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
  };
  url: '/api/v1/clubs/{club_id}/activities/';
};

export type GetClubActivitiesApiV1ClubsClubIdActivitiesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetClubActivitiesApiV1ClubsClubIdActivitiesGetError =
  GetClubActivitiesApiV1ClubsClubIdActivitiesGetErrors[keyof GetClubActivitiesApiV1ClubsClubIdActivitiesGetErrors];

export type GetClubActivitiesApiV1ClubsClubIdActivitiesGetResponses = {
  /**
   * Successful Response
   */
  200: PageResponseActivityInfo;
};

export type GetClubActivitiesApiV1ClubsClubIdActivitiesGetResponse =
  GetClubActivitiesApiV1ClubsClubIdActivitiesGetResponses[keyof GetClubActivitiesApiV1ClubsClubIdActivitiesGetResponses];

export type CreateClubActivityApiV1ClubsClubIdActivitiesPostData = {
  body: ActivityCreate;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/api/v1/clubs/{club_id}/activities/';
};

export type CreateClubActivityApiV1ClubsClubIdActivitiesPostErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateClubActivityApiV1ClubsClubIdActivitiesPostError =
  CreateClubActivityApiV1ClubsClubIdActivitiesPostErrors[keyof CreateClubActivityApiV1ClubsClubIdActivitiesPostErrors];

export type CreateClubActivityApiV1ClubsClubIdActivitiesPostResponses = {
  /**
   * Successful Response
   */
  201: ActivityInfo;
};

export type CreateClubActivityApiV1ClubsClubIdActivitiesPostResponse =
  CreateClubActivityApiV1ClubsClubIdActivitiesPostResponses[keyof CreateClubActivityApiV1ClubsClubIdActivitiesPostResponses];

export type ListTermsApiV1AdminAcademicTermsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/admin/academic_terms/';
};

export type ListTermsApiV1AdminAcademicTermsGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Permission Denied
   */
  403: unknown;
};

export type ListTermsApiV1AdminAcademicTermsGetResponses = {
  /**
   * Response List Terms Api V1 Admin Academic Terms  Get
   *
   * Successful Response
   */
  200: Array<AcademicTermInfo>;
};

export type ListTermsApiV1AdminAcademicTermsGetResponse =
  ListTermsApiV1AdminAcademicTermsGetResponses[keyof ListTermsApiV1AdminAcademicTermsGetResponses];

export type CreateTermApiV1AdminAcademicTermsPostData = {
  body: AcademicTermCreate;
  path?: never;
  query?: never;
  url: '/api/v1/admin/academic_terms/';
};

export type CreateTermApiV1AdminAcademicTermsPostErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Permission Denied
   */
  403: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTermApiV1AdminAcademicTermsPostError =
  CreateTermApiV1AdminAcademicTermsPostErrors[keyof CreateTermApiV1AdminAcademicTermsPostErrors];

export type CreateTermApiV1AdminAcademicTermsPostResponses = {
  /**
   * Successful Response
   */
  200: AcademicTermInfo;
};

export type CreateTermApiV1AdminAcademicTermsPostResponse =
  CreateTermApiV1AdminAcademicTermsPostResponses[keyof CreateTermApiV1AdminAcademicTermsPostResponses];

export type DeleteTermApiV1AdminAcademicTermsTermIdDeleteData = {
  body?: never;
  path: {
    /**
     * Term Id
     */
    term_id: number;
  };
  query?: never;
  url: '/api/v1/admin/academic_terms/{term_id}';
};

export type DeleteTermApiV1AdminAcademicTermsTermIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Permission Denied
   */
  403: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTermApiV1AdminAcademicTermsTermIdDeleteError =
  DeleteTermApiV1AdminAcademicTermsTermIdDeleteErrors[keyof DeleteTermApiV1AdminAcademicTermsTermIdDeleteErrors];

export type DeleteTermApiV1AdminAcademicTermsTermIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: AcademicTermInfo;
};

export type DeleteTermApiV1AdminAcademicTermsTermIdDeleteResponse =
  DeleteTermApiV1AdminAcademicTermsTermIdDeleteResponses[keyof DeleteTermApiV1AdminAcademicTermsTermIdDeleteResponses];

export type GetTermApiV1AdminAcademicTermsTermIdGetData = {
  body?: never;
  path: {
    /**
     * Term Id
     */
    term_id: number;
  };
  query?: never;
  url: '/api/v1/admin/academic_terms/{term_id}';
};

export type GetTermApiV1AdminAcademicTermsTermIdGetErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Permission Denied
   */
  403: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTermApiV1AdminAcademicTermsTermIdGetError =
  GetTermApiV1AdminAcademicTermsTermIdGetErrors[keyof GetTermApiV1AdminAcademicTermsTermIdGetErrors];

export type GetTermApiV1AdminAcademicTermsTermIdGetResponses = {
  /**
   * Successful Response
   */
  200: AcademicTermInfo;
};

export type GetTermApiV1AdminAcademicTermsTermIdGetResponse =
  GetTermApiV1AdminAcademicTermsTermIdGetResponses[keyof GetTermApiV1AdminAcademicTermsTermIdGetResponses];

export type UpdateTermApiV1AdminAcademicTermsTermIdPatchData = {
  body: AcademicTermUpdate;
  path: {
    /**
     * Term Id
     */
    term_id: number;
  };
  query?: never;
  url: '/api/v1/admin/academic_terms/{term_id}';
};

export type UpdateTermApiV1AdminAcademicTermsTermIdPatchErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Permission Denied
   */
  403: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTermApiV1AdminAcademicTermsTermIdPatchError =
  UpdateTermApiV1AdminAcademicTermsTermIdPatchErrors[keyof UpdateTermApiV1AdminAcademicTermsTermIdPatchErrors];

export type UpdateTermApiV1AdminAcademicTermsTermIdPatchResponses = {
  /**
   * Successful Response
   */
  200: AcademicTermInfo;
};

export type UpdateTermApiV1AdminAcademicTermsTermIdPatchResponse =
  UpdateTermApiV1AdminAcademicTermsTermIdPatchResponses[keyof UpdateTermApiV1AdminAcademicTermsTermIdPatchResponses];

export type ListActivitiesApiV1GeneralActivitiesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search
     */
    search?: string | null;
    /**
     * Level
     */
    level?: GeneralActivityLevelEnum | null;
  };
  url: '/api/v1/general-activities/';
};

export type ListActivitiesApiV1GeneralActivitiesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListActivitiesApiV1GeneralActivitiesGetError =
  ListActivitiesApiV1GeneralActivitiesGetErrors[keyof ListActivitiesApiV1GeneralActivitiesGetErrors];

export type ListActivitiesApiV1GeneralActivitiesGetResponses = {
  /**
   * Response List Activities Api V1 General Activities  Get
   *
   * Successful Response
   */
  200: Array<GeneralActivityInfo>;
};

export type ListActivitiesApiV1GeneralActivitiesGetResponse =
  ListActivitiesApiV1GeneralActivitiesGetResponses[keyof ListActivitiesApiV1GeneralActivitiesGetResponses];

export type CreateApiV1GeneralActivitiesPostData = {
  body: GeneralActivityCreate;
  path?: never;
  query?: never;
  url: '/api/v1/general-activities/';
};

export type CreateApiV1GeneralActivitiesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateApiV1GeneralActivitiesPostError =
  CreateApiV1GeneralActivitiesPostErrors[keyof CreateApiV1GeneralActivitiesPostErrors];

export type CreateApiV1GeneralActivitiesPostResponses = {
  /**
   * Successful Response
   */
  200: GeneralActivityInfo;
};

export type CreateApiV1GeneralActivitiesPostResponse =
  CreateApiV1GeneralActivitiesPostResponses[keyof CreateApiV1GeneralActivitiesPostResponses];

export type DeleteApiV1GeneralActivitiesActivityIdDeleteData = {
  body?: never;
  path: {
    /**
     * Activity Id
     */
    activity_id: number;
  };
  query?: never;
  url: '/api/v1/general-activities/{activity_id}';
};

export type DeleteApiV1GeneralActivitiesActivityIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteApiV1GeneralActivitiesActivityIdDeleteError =
  DeleteApiV1GeneralActivitiesActivityIdDeleteErrors[keyof DeleteApiV1GeneralActivitiesActivityIdDeleteErrors];

export type DeleteApiV1GeneralActivitiesActivityIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: GeneralActivityInfo;
};

export type DeleteApiV1GeneralActivitiesActivityIdDeleteResponse =
  DeleteApiV1GeneralActivitiesActivityIdDeleteResponses[keyof DeleteApiV1GeneralActivitiesActivityIdDeleteResponses];

export type GetApiV1GeneralActivitiesActivityIdGetData = {
  body?: never;
  path: {
    /**
     * Activity Id
     */
    activity_id: number;
  };
  query?: never;
  url: '/api/v1/general-activities/{activity_id}';
};

export type GetApiV1GeneralActivitiesActivityIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetApiV1GeneralActivitiesActivityIdGetError =
  GetApiV1GeneralActivitiesActivityIdGetErrors[keyof GetApiV1GeneralActivitiesActivityIdGetErrors];

export type GetApiV1GeneralActivitiesActivityIdGetResponses = {
  /**
   * Successful Response
   */
  200: GeneralActivityInfo;
};

export type GetApiV1GeneralActivitiesActivityIdGetResponse =
  GetApiV1GeneralActivitiesActivityIdGetResponses[keyof GetApiV1GeneralActivitiesActivityIdGetResponses];

export type UpdateApiV1GeneralActivitiesActivityIdPatchData = {
  body: GeneralActivityUpdate;
  path: {
    /**
     * Activity Id
     */
    activity_id: number;
  };
  query?: never;
  url: '/api/v1/general-activities/{activity_id}';
};

export type UpdateApiV1GeneralActivitiesActivityIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateApiV1GeneralActivitiesActivityIdPatchError =
  UpdateApiV1GeneralActivitiesActivityIdPatchErrors[keyof UpdateApiV1GeneralActivitiesActivityIdPatchErrors];

export type UpdateApiV1GeneralActivitiesActivityIdPatchResponses = {
  /**
   * Successful Response
   */
  200: GeneralActivityInfo;
};

export type UpdateApiV1GeneralActivitiesActivityIdPatchResponse =
  UpdateApiV1GeneralActivitiesActivityIdPatchResponses[keyof UpdateApiV1GeneralActivitiesActivityIdPatchResponses];
