import { useId, useMemo } from "react";
import MarkdownPreview, {
  type MarkdownPreviewProps,
} from "@uiw/react-markdown-preview/nohighlight";
import { IconLink } from "@tabler/icons-react";
import remarkBreaks from "remark-breaks";
import { rehypeSanitizeWithFragments } from "../../lib/markdown";
import "./Markdown.css";

const components: MarkdownPreviewProps["components"] = {
  a: ({ node, children, ...props }) => {
    // Restore only the empty heading anchor generated by the preview library.
    // Its URL has already passed through sanitization and namespace rewriting.
    if (node?.properties.tabIndex === -1 && !node.children.length && props.href?.startsWith("#")) {
      return (
        <a {...props} className="anchor" aria-hidden="true">
          <IconLink size={16} className="octicon-link" />
        </a>
      );
    }
    return <a {...props}>{children}</a>;
  },
};

export function MarkdownContent({ value }: { value: string }) {
  const namespace = useId();
  const rehypePlugins = useMemo(() => [() => rehypeSanitizeWithFragments(namespace)], [namespace]);
  return (
    <MarkdownPreview
      className="markdown-content"
      source={value}
      skipHtml
      disableCopy
      remarkPlugins={[remarkBreaks]}
      rehypePlugins={rehypePlugins}
      components={components}
    />
  );
}
