"""empty message

Revision ID: 09734045808e
Revises: fc9178f84916
Create Date: 2026-05-04 09:15:58.945363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09734045808e'
down_revision: Union[str, Sequence[str], None] = 'fc9178f84916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_only_one_current'), table_name='academic_term', postgresql_where='(is_current IS TRUE)')
    op.create_index('ix_only_one_current', 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.create_index('ix_single_pending_club_activity_update_request', 'club_activity_update_request', ['club_activity_id'], unique=True, postgresql_where=sa.text("moderate_status = 'pending'"))
    op.create_index('ix_single_pending_club_update_request', 'club_update_request', ['club_id'], unique=True, postgresql_where=sa.text("moderate_status = 'pending'"))
    op.drop_index(op.f('ix_unique_active_club_name'), table_name='clubs', postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.create_index('ix_unique_active_club_name', 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.create_index('ix_single_pending_user_update_request', 'user_update_request', ['user_id'], unique=True, postgresql_where=sa.text("moderate_status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_single_pending_user_update_request', table_name='user_update_request', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.drop_index('ix_unique_active_club_name', table_name='clubs')
    op.create_index(op.f('ix_unique_active_club_name'), 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.drop_index('ix_single_pending_club_update_request', table_name='club_update_request', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.drop_index('ix_single_pending_club_activity_update_request', table_name='club_activity_update_request', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.drop_index('ix_only_one_current', table_name='academic_term')
    op.create_index(op.f('ix_only_one_current'), 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    # ### end Alembic commands ###
