"""rename_club_activity_table

Revision ID: 0d0985e9223c
Revises: 485c04525f54
Create Date: 2026-05-25 09:09:37.947924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d0985e9223c'
down_revision: Union[str, Sequence[str], None] = '485c04525f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_activities',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('picture_urls', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_club_activities_check_start_end_time')),
    sa.ForeignKeyConstraint(['academic_term_id'], ['app.academic_term.id'], name=op.f('fk_club_activities_academic_term_id_academic_term')),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_club_activities_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_activities')),
    schema='app'
    )
    op.create_index(op.f('ix_club_activities_name'), 'club_activities', ['name'], unique=False, schema='app')
    op.create_table('club_activity_participators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_activity_id'], ['app.club_activities.id'], name=op.f('fk_club_activity_participators_club_activity_id_club_activities')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('fk_club_activity_participators_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'club_activity_id', name=op.f('pk_club_activity_participators')),
    schema='app'
    )
    op.create_foreign_key(op.f('fk_club_activity_update_request_club_activity_id_club_activities'), 'club_activity_update_request', 'club_activities', ['club_activity_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')

    op.drop_table('activity_participators', schema='app')
    op.drop_constraint(op.f('fk_club_activity_update_request_club_activity_id_activities'), 'club_activity_update_request', type_='foreignkey', schema='app')
    op.drop_index(op.f('ix_activities_name'), table_name='activities', schema='app')
    op.drop_table('activities', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_activity_participators', schema='app')
    op.drop_constraint(op.f('fk_club_activity_update_request_club_activity_id_club_activities'), 'club_activity_update_request', schema='app', type_='foreignkey')
    op.drop_index(op.f('ix_club_activities_name'), table_name='club_activities', schema='app')
    op.drop_table('club_activities', schema='app')

    op.create_table('activities',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('picture_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('academic_term_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_activities_check_start_end_time')),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], name=op.f('fk_activities_academic_term_id_academic_term')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_activities_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    schema='app'
    )
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=False, schema='app')
    op.create_foreign_key(op.f('fk_club_activity_update_request_club_activity_id_activities'), 'club_activity_update_request', 'activities', ['club_activity_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_table('activity_participators',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_participators_activity_id_activities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_participators_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'activity_id', name=op.f('pk_activity_participators')),
    schema='app'
    )
    # ### end Alembic commands ###
