"""${MESSAGE:-auto revision}

Revision ID: 1907c33954fc
Revises: 50a930fe728d
Create Date: 2026-05-15 09:18:58.508271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1907c33954fc'
down_revision: Union[str, Sequence[str], None] = '50a930fe728d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_index(op.f('ix_only_one_current'), table_name='academic_term', postgresql_where='(is_current IS TRUE)')
    op.create_index('ix_only_one_current', 'academic_term', [sa.literal_column('CASE WHEN is_current THEN true END')], unique=True, schema='app')
    op.drop_constraint(op.f('fk_activities_club_id_clubs'), 'activities', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_gen_act_records_academic_term_id'), 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('fk_activities_academic_term_id_academic_term'), 'activities', 'academic_term', ['academic_term_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_activities_club_id_clubs'), 'activities', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_activity_participators_user_id_users'), 'activity_participators', type_='foreignkey')
    op.drop_constraint(op.f('fk_activity_participators_activity_id_activities'), 'activity_participators', type_='foreignkey')
    op.create_foreign_key(op.f('fk_activity_participators_activity_id_activities'), 'activity_participators', 'activities', ['activity_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_activity_participators_user_id_users'), 'activity_participators', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_club_activity_create_request_moderator_id_users'), 'club_activity_create_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_request_club_id_clubs'), 'club_activity_create_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_create_request_moderator_id_users'), 'club_activity_create_request', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', 'users', ['requestor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_activity_create_request_club_id_clubs'), 'club_activity_create_request', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_club_activity_update_request_moderator_id_users'), 'club_activity_update_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_request_club_activity_id_activities'), 'club_activity_update_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', 'users', ['requestor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_activity_update_request_moderator_id_users'), 'club_activity_update_request', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_activity_update_request_club_activity_id_activities'), 'club_activity_update_request', 'activities', ['club_activity_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_club_general_activity_records_activity_id_general_activities'), 'club_general_activity_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_general_activity_records_club_id_clubs'), 'club_general_activity_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_general_activity_records_auditor_id_users'), 'club_general_activity_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_general_activity_records_activity_id_general_activities'), 'club_general_activity_records', 'general_activities', ['activity_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_general_activity_records_auditor_id_users'), 'club_general_activity_records', 'users', ['auditor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_general_activity_records_club_id_clubs'), 'club_general_activity_records', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_club_members_club_id_clubs'), 'club_members', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_members_user_id_users'), 'club_members', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_members_club_id_clubs'), 'club_members', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_members_user_id_users'), 'club_members', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_club_tags_club_id_clubs'), 'club_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_tags_tag_id_tags'), 'club_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_tags_tag_id_tags'), 'club_tags', 'tags', ['tag_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_tags_club_id_clubs'), 'club_tags', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_club_update_request_moderator_id_users'), 'club_update_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_request_requestor_id_users'), 'club_update_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_request_club_id_clubs'), 'club_update_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_update_request_moderator_id_users'), 'club_update_request', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_update_request_requestor_id_users'), 'club_update_request', 'users', ['requestor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_update_request_club_id_clubs'), 'club_update_request', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_index(op.f('ix_unique_active_club_name'), table_name='clubs', postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.create_index('ix_unique_active_club_name', 'clubs', [sa.literal_column("CASE WHEN (status != 'archived') THEN name END")], unique=True, schema='app')
    op.drop_constraint(op.f('fk_club_gen_act_records_academic_term_id'), 'general_activities', type_='foreignkey')
    op.create_foreign_key(op.f('fk_general_activities_academic_term_id_academic_term'), 'general_activities', 'academic_term', ['academic_term_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_record_condition_details_condition_id_activity_conditions'), 'record_condition_details', type_='foreignkey')
    op.drop_constraint(op.f('fk_record_condition_details_record_id_club_general_acti_ac66'), 'record_condition_details', type_='foreignkey')
    op.create_foreign_key(op.f('fk_record_condition_details_record_id_club_general_activity_records'), 'record_condition_details', 'club_general_activity_records', ['record_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_record_condition_details_condition_id_activity_conditions'), 'record_condition_details', 'activity_conditions', ['condition_id'], ['id'], source_schema='app', referent_schema='app', ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_star_level_applications_club_id_clubs'), 'star_level_applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_star_level_applications_auditor_id_users'), 'star_level_applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_star_level_applications_academic_term_id_academic_term'), 'star_level_applications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_star_level_applications_auditor_id_users'), 'star_level_applications', 'users', ['auditor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_star_level_applications_academic_term_id_academic_term'), 'star_level_applications', 'academic_term', ['academic_term_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_star_level_applications_club_id_clubs'), 'star_level_applications', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_user_update_request_user_id_users'), 'user_update_request', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_update_request_moderator_id_users'), 'user_update_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_update_request_moderator_id_users'), 'user_update_request', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_user_update_request_user_id_users'), 'user_update_request', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_update_request_user_id_users'), 'user_update_request', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_update_request_moderator_id_users'), 'user_update_request', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_update_request_moderator_id_users'), 'user_update_request', 'users', ['moderator_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_update_request_user_id_users'), 'user_update_request', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_star_level_applications_club_id_clubs'), 'star_level_applications', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_star_level_applications_academic_term_id_academic_term'), 'star_level_applications', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_star_level_applications_auditor_id_users'), 'star_level_applications', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_star_level_applications_academic_term_id_academic_term'), 'star_level_applications', 'academic_term', ['academic_term_id'], ['id'])
    op.create_foreign_key(op.f('fk_star_level_applications_auditor_id_users'), 'star_level_applications', 'users', ['auditor_id'], ['id'])
    op.create_foreign_key(op.f('fk_star_level_applications_club_id_clubs'), 'star_level_applications', 'clubs', ['club_id'], ['id'])
    op.drop_constraint(op.f('fk_record_condition_details_condition_id_activity_conditions'), 'record_condition_details', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_record_condition_details_record_id_club_general_activity_records'), 'record_condition_details', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_record_condition_details_record_id_club_general_acti_ac66'), 'record_condition_details', 'club_general_activity_records', ['record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_record_condition_details_condition_id_activity_conditions'), 'record_condition_details', 'activity_conditions', ['condition_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('fk_general_activities_academic_term_id_academic_term'), 'general_activities', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_gen_act_records_academic_term_id'), 'general_activities', 'academic_term', ['academic_term_id'], ['id'])
    op.drop_index('ix_unique_active_club_name', table_name='clubs', schema='app')
    op.create_index(op.f('ix_unique_active_club_name'), 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.drop_constraint(op.f('fk_club_update_request_club_id_clubs'), 'club_update_request', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_request_requestor_id_users'), 'club_update_request', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_request_moderator_id_users'), 'club_update_request', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_update_request_club_id_clubs'), 'club_update_request', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_update_request_requestor_id_users'), 'club_update_request', 'users', ['requestor_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_update_request_moderator_id_users'), 'club_update_request', 'users', ['moderator_id'], ['id'])
    op.drop_constraint(op.f('fk_club_tags_club_id_clubs'), 'club_tags', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_tags_tag_id_tags'), 'club_tags', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_tags_tag_id_tags'), 'club_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_tags_club_id_clubs'), 'club_tags', 'clubs', ['club_id'], ['id'])
    op.drop_constraint(op.f('fk_club_members_user_id_users'), 'club_members', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_members_club_id_clubs'), 'club_members', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_members_user_id_users'), 'club_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_members_club_id_clubs'), 'club_members', 'clubs', ['club_id'], ['id'])
    op.drop_constraint(op.f('fk_club_general_activity_records_club_id_clubs'), 'club_general_activity_records', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_general_activity_records_auditor_id_users'), 'club_general_activity_records', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_general_activity_records_activity_id_general_activities'), 'club_general_activity_records', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_general_activity_records_auditor_id_users'), 'club_general_activity_records', 'users', ['auditor_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_general_activity_records_club_id_clubs'), 'club_general_activity_records', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_general_activity_records_activity_id_general_activities'), 'club_general_activity_records', 'general_activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_club_activity_update_request_club_activity_id_activities'), 'club_activity_update_request', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_request_moderator_id_users'), 'club_activity_update_request', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', 'users', ['requestor_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_activity_update_request_club_activity_id_activities'), 'club_activity_update_request', 'activities', ['club_activity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_activity_update_request_moderator_id_users'), 'club_activity_update_request', 'users', ['moderator_id'], ['id'])
    op.drop_constraint(op.f('fk_club_activity_create_request_club_id_clubs'), 'club_activity_create_request', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_request_moderator_id_users'), 'club_activity_create_request', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', 'users', ['requestor_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_activity_create_request_club_id_clubs'), 'club_activity_create_request', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_activity_create_request_moderator_id_users'), 'club_activity_create_request', 'users', ['moderator_id'], ['id'])
    op.drop_constraint(op.f('fk_activity_participators_user_id_users'), 'activity_participators', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_activity_participators_activity_id_activities'), 'activity_participators', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_activity_participators_activity_id_activities'), 'activity_participators', 'activities', ['activity_id'], ['id'])
    op.create_foreign_key(op.f('fk_activity_participators_user_id_users'), 'activity_participators', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_activities_club_id_clubs'), 'activities', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_activities_academic_term_id_academic_term'), 'activities', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_gen_act_records_academic_term_id'), 'activities', 'academic_term', ['academic_term_id'], ['id'])
    op.create_foreign_key(op.f('fk_activities_club_id_clubs'), 'activities', 'clubs', ['club_id'], ['id'])
    op.drop_index('ix_only_one_current', table_name='academic_term', schema='app')
    op.create_index(op.f('ix_only_one_current'), 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
