"""empty message

Revision ID: 2d19f795b866
Revises: 8cb927d591fd
Create Date: 2026-04-25 11:46:18.402449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d19f795b866'
down_revision: Union[str, Sequence[str], None] = '8cb927d591fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_update_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_uri', sa.Text, nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_update_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.TEXT(), nullable=True))
        batch_op.drop_column('avatar_uri')

    # ### end Alembic commands ###
