"""auto revision

Revision ID: 485c04525f54
Revises:
Create Date: 2026-05-22 05:52:46.691593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485c04525f54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions")

    op.create_table('academic_term',
    sa.Column('term_name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_term')),
    sa.UniqueConstraint('term_name', name=op.f('uq_academic_term_term_name')),
    schema='app'
    )
    op.create_index('ix_only_one_current', 'academic_term', ['is_current'], unique=True, schema='app', postgresql_where=sa.text('is_current = true'))
    op.create_table('activity_conditions',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_conditions')),
    schema='app'
    )
    op.create_table('clubs',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('unreviewed', 'normal', 'archived', name='clubstatusenum'), nullable=False),
    sa.Column('star_level', sa.Enum('none', 'one_star', 'two_star', 'three_star', 'four_star', 'five_star', 'honorary', name='clubstarlevelenum'), nullable=False),
    sa.Column('category', sa.Enum('sports', 'humanity', 'arts', 'science', 'charity', 'business', 'campus', 'other', name='clubcategoryenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs')),
    schema='app'
    )
    op.create_index('ix_clubs_description_trgm', 'clubs', ['description'], unique=False, schema='app', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False, schema='app')
    op.create_index('ix_clubs_name_trgm', 'clubs', ['name'], unique=False, schema='app', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_clubs_summary_trgm', 'clubs', ['summary'], unique=False, schema='app', postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
    op.create_index('ix_unique_active_club_name', 'clubs', ['name'], unique=True, schema='app', postgresql_where=sa.text("status != 'archived'"))
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('normal', 'archived', name='tagstatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    schema='app'
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True, schema='app')
    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_uri', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('real_name', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ban', 'user', 'moderator', 'scf', 'admin', 'dev', name='roleenum'), nullable=False),
    sa.Column('wecom_userid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    schema='app'
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True, schema='app')
    op.create_index(op.f('ix_users_wecom_userid'), 'users', ['wecom_userid'], unique=True, schema='app')
    op.create_table('activities',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('picture_urls', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_activities_check_start_end_time')),
    sa.ForeignKeyConstraint(['academic_term_id'], ['app.academic_term.id'], name=op.f('fk_activities_academic_term_id_academic_term')),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_activities_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    schema='app'
    )
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=False, schema='app')
    op.create_table('club_activity_create_request',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', sa.Enum('pending', 'approved', 'rejected', 'superseded', name='moderatestatusenum'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_club_activity_create_request_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['app.users.id'], name=op.f('fk_club_activity_create_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['requestor_id'], ['app.users.id'], name=op.f('fk_club_activity_create_request_requestor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_activity_create_request')),
    schema='app'
    )
    op.create_table('club_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('membership', sa.Enum('pending', 'member', 'president', 'vice president', 'left', name='clubmembershipenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_club_members_club_id_clubs')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('fk_club_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_members')),
    sa.UniqueConstraint('club_id', 'user_id', name='uix_club_id_user_id'),
    schema='app'
    )
    op.create_table('club_tags',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_club_tags_club_id_clubs')),
    sa.ForeignKeyConstraint(['tag_id'], ['app.tags.id'], name=op.f('fk_club_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('club_id', 'tag_id', name=op.f('pk_club_tags')),
    schema='app'
    )
    op.create_table('club_update_request',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_uri', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', sa.Enum('pending', 'approved', 'rejected', 'superseded', name='moderatestatusenum'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_club_update_request_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['app.users.id'], name=op.f('fk_club_update_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['requestor_id'], ['app.users.id'], name=op.f('fk_club_update_request_requestor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_update_request')),
    schema='app'
    )
    op.create_index('ix_single_pending_club_update_request', 'club_update_request', ['club_id'], unique=True, schema='app', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.create_table('general_activities',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('school', 'large', 'club_federation', name='generalactivitylevelenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['app.academic_term.id'], name=op.f('fk_general_activities_academic_term_id_academic_term')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_activities')),
    schema='app'
    )
    op.create_index(op.f('ix_general_activities_name'), 'general_activities', ['name'], unique=False, schema='app')
    op.create_table('star_level_applications',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('contest_attachment', sa.Text(), nullable=True),
    sa.Column('requested_contest_score', sa.Integer(), nullable=True),
    sa.Column('final_contest_score', sa.Integer(), nullable=True),
    sa.Column('uniqueness_statement', sa.Text(), nullable=True),
    sa.Column('uniqueness_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_score', sa.Integer(), nullable=True),
    sa.Column('approved_level', sa.Enum('none', 'one_star', 'two_star', 'three_star', 'four_star', 'five_star', 'honorary', name='clubstarlevelenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('audit_status', sa.Enum('pending', 'approved', 'rejected', name='auditstatusenum'), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_term_id'], ['app.academic_term.id'], name=op.f('fk_star_level_applications_academic_term_id_academic_term')),
    sa.ForeignKeyConstraint(['auditor_id'], ['app.users.id'], name=op.f('fk_star_level_applications_auditor_id_users')),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_star_level_applications_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_star_level_applications')),
    sa.UniqueConstraint('club_id', 'academic_term_id', name=op.f('uq_star_level_applications_club_id_academic_term_id')),
    schema='app'
    )
    op.create_table('user_update_request',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('avatar_uri', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', sa.Enum('pending', 'approved', 'rejected', 'superseded', name='moderatestatusenum'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['app.users.id'], name=op.f('fk_user_update_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('fk_user_update_request_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_update_request')),
    schema='app'
    )
    op.create_index('ix_single_pending_user_update_request', 'user_update_request', ['user_id'], unique=True, schema='app', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.create_table('activity_participators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['app.activities.id'], name=op.f('fk_activity_participators_activity_id_activities')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('fk_activity_participators_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'activity_id', name=op.f('pk_activity_participators')),
    schema='app'
    )
    op.create_table('club_activity_update_request',
    sa.Column('club_activity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('picture_urls', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', sa.Enum('pending', 'approved', 'rejected', 'superseded', name='moderatestatusenum'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_activity_id'], ['app.activities.id'], name=op.f('fk_club_activity_update_request_club_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['app.users.id'], name=op.f('fk_club_activity_update_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['requestor_id'], ['app.users.id'], name=op.f('fk_club_activity_update_request_requestor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_activity_update_request')),
    schema='app'
    )
    op.create_index('ix_single_pending_club_activity_update_request', 'club_activity_update_request', ['club_activity_id'], unique=True, schema='app', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.create_table('club_general_activity_records',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('participation_type', sa.Enum('participate_only', 'organize', name='participationtypeenum'), nullable=False),
    sa.Column('requested_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('proof_files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_status', sa.Enum('pending', 'approved', 'rejected', name='auditstatusenum'), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['app.general_activities.id'], name=op.f('fk_club_general_activity_records_activity_id_general_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auditor_id'], ['app.users.id'], name=op.f('fk_club_general_activity_records_auditor_id_users')),
    sa.ForeignKeyConstraint(['club_id'], ['app.clubs.id'], name=op.f('fk_club_general_activity_records_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_general_activity_records')),
    schema='app'
    )
    op.create_index(op.f('ix_club_general_activity_records_activity_id'), 'club_general_activity_records', ['activity_id'], unique=False, schema='app')
    op.create_index(op.f('ix_club_general_activity_records_club_id'), 'club_general_activity_records', ['club_id'], unique=False, schema='app')
    op.create_index('ix_unique_club_activity_record', 'club_general_activity_records', ['club_id', 'activity_id'], unique=True, schema='app')
    op.create_table('record_condition_details',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('is_met', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['app.activity_conditions.id'], name=op.f('fk_record_condition_details_condition_id_activity_conditions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['app.club_general_activity_records.id'], name=op.f('fk_record_condition_details_record_id_club_general_activity_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_condition_details')),
    schema='app'
    )
    op.create_index(op.f('ix_record_condition_details_condition_id'), 'record_condition_details', ['condition_id'], unique=False, schema='app')
    op.create_index(op.f('ix_record_condition_details_record_id'), 'record_condition_details', ['record_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_condition_details_record_id'), table_name='record_condition_details', schema='app')
    op.drop_index(op.f('ix_record_condition_details_condition_id'), table_name='record_condition_details', schema='app')
    op.drop_table('record_condition_details', schema='app')
    op.drop_index('ix_unique_club_activity_record', table_name='club_general_activity_records', schema='app')
    op.drop_index(op.f('ix_club_general_activity_records_club_id'), table_name='club_general_activity_records', schema='app')
    op.drop_index(op.f('ix_club_general_activity_records_activity_id'), table_name='club_general_activity_records', schema='app')
    op.drop_table('club_general_activity_records', schema='app')
    op.drop_index('ix_single_pending_club_activity_update_request', table_name='club_activity_update_request', schema='app', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.drop_table('club_activity_update_request', schema='app')
    op.drop_table('activity_participators', schema='app')
    op.drop_index('ix_single_pending_user_update_request', table_name='user_update_request', schema='app', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.drop_table('user_update_request', schema='app')
    op.drop_table('star_level_applications', schema='app')
    op.drop_index(op.f('ix_general_activities_name'), table_name='general_activities', schema='app')
    op.drop_table('general_activities', schema='app')
    op.drop_index('ix_single_pending_club_update_request', table_name='club_update_request', schema='app', postgresql_where=sa.text("moderate_status = 'pending'"))
    op.drop_table('club_update_request', schema='app')
    op.drop_table('club_tags', schema='app')
    op.drop_table('club_members', schema='app')
    op.drop_table('club_activity_create_request', schema='app')
    op.drop_index(op.f('ix_activities_name'), table_name='activities', schema='app')
    op.drop_table('activities', schema='app')
    op.drop_index(op.f('ix_users_wecom_userid'), table_name='users', schema='app')
    op.drop_index(op.f('ix_users_username'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    op.drop_index(op.f('ix_tags_name'), table_name='tags', schema='app')
    op.drop_table('tags', schema='app')
    op.drop_index('ix_unique_active_club_name', table_name='clubs', schema='app')
    op.drop_index('ix_clubs_summary_trgm', table_name='clubs', schema='app', postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
    op.drop_index('ix_clubs_name_trgm', table_name='clubs', schema='app', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs', schema='app')
    op.drop_index('ix_clubs_description_trgm', table_name='clubs', schema='app', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_table('clubs', schema='app')
    op.drop_table('activity_conditions', schema='app')
    op.drop_index('ix_only_one_current', table_name='academic_term', schema='app')
    op.drop_table('academic_term', schema='app')
    # ### end Alembic commands ###
