"""empty message

Revision ID: 56129826055b
Revises: d1549c8fd5a9
Create Date: 2026-04-23 21:03:20.817839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56129826055b'
down_revision: Union[str, Sequence[str], None] = 'd1549c8fd5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_update_request',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', sa.Enum('pending', 'approved', 'rejected', name='moderatestateenum'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_user_update_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_update_request_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_update_request'))
    )
    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('school', 'large', 'federation', name='generalactivitylevelenum'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.Enum('ban', 'user', 'scf', 'admin', 'dev', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ban', 'user', 'scf', 'admin', 'dev', name='roleenum'),
               type_=sa.VARCHAR(length=21),
               existing_nullable=False)

    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.Enum('school', 'large', 'federation', name='generalactivitylevelenum'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    op.drop_table('user_update_request')
    # ### end Alembic commands ###
