"""empty message

Revision ID: 572cc8a731c5
Revises: 980bd7ea8cc3
Create Date: 2026-05-02 01:18:44.399548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572cc8a731c5'
down_revision: Union[str, Sequence[str], None] = '980bd7ea8cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_only_one_current'), table_name='academic_term', postgresql_where='(is_current IS TRUE)')
    op.create_index('ix_only_one_current', 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.add_column('club_activity_create_request', sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', 'users', ['requestor_id'], ['id'])
    op.add_column('club_activity_update_request', sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', 'users', ['requestor_id'], ['id'])
    op.drop_index(op.f('ix_unique_active_club_name'), table_name='clubs', postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.create_index('ix_unique_active_club_name', 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_active_club_name', table_name='clubs')
    op.create_index(op.f('ix_unique_active_club_name'), 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.drop_constraint(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_request', 'users', ['requestor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('club_activity_update_request', 'request_at')
    op.drop_constraint(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_request', 'users', ['requestor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('club_activity_create_request', 'request_at')
    op.drop_index('ix_only_one_current', table_name='academic_term')
    op.create_index(op.f('ix_only_one_current'), 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    # ### end Alembic commands ###
