"""empty message

Revision ID: 6aa866f8a18c
Revises: e4e4483e127f
Create Date: 2026-04-07 15:27:40.308487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa866f8a18c'
down_revision: Union[str, Sequence[str], None] = 'e4e4483e127f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_term_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_club_gen_act_records_academic_term_id', 'academic_term', ['academic_term_id'], ['id'])

    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('academic_term_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_club_gen_act_records_academic_term_id', 'academic_term', ['academic_term_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_club_gen_act_records_academic_term_id', type_='foreignkey')
        batch_op.drop_column('academic_term_id')
        batch_op.drop_column('requested_score')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_club_gen_act_records_academic_term_id', type_='foreignkey')
        batch_op.drop_column('academic_term_id')

    # ### end Alembic commands ###
