"""fix_foreign_keys

Revision ID: 8b9b0e11982e
Revises: ce5b0aba4d25
Create Date: 2026-05-25 15:11:47.967057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9b0e11982e'
down_revision: Union[str, Sequence[str], None] = 'ce5b0aba4d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_request_club_id_clubs'), 'club_activity_create_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_request_moderator_id_users'), 'club_activity_create_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_create_requests_requestor_id_users'), 'club_activity_create_requests', 'users', ['requestor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_activity_create_requests_club_id_clubs'), 'club_activity_create_requests', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_activity_create_requests_moderator_id_users'), 'club_activity_create_requests', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_club_activity_participators_user_id_users'), 'club_activity_participants', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_participators_club_activity_id_club_activities'), 'club_activity_participants', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_participants_user_id_users'), 'club_activity_participants', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_activity_participants_club_activity_id_club_activities'), 'club_activity_participants', 'club_activities', ['club_activity_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_club_activity_update_request_club_activity_id_club_a_c5cc'), 'club_activity_update_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_request_moderator_id_users'), 'club_activity_update_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_update_requests_requestor_id_users'), 'club_activity_update_requests', 'users', ['requestor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_activity_update_requests_club_activity_id_club_activities'), 'club_activity_update_requests', 'club_activities', ['club_activity_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_activity_update_requests_moderator_id_users'), 'club_activity_update_requests', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_constraint(op.f('fk_club_update_request_club_id_clubs'), 'club_update_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_request_moderator_id_users'), 'club_update_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_request_requestor_id_users'), 'club_update_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_update_requests_requestor_id_users'), 'club_update_requests', 'users', ['requestor_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_update_requests_moderator_id_users'), 'club_update_requests', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_club_update_requests_club_id_clubs'), 'club_update_requests', 'clubs', ['club_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_update_request_user_id_users'), 'user_update_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_update_request_moderator_id_users'), 'user_update_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_update_requests_moderator_id_users'), 'user_update_requests', 'users', ['moderator_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(op.f('fk_user_update_requests_user_id_users'), 'user_update_requests', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_update_requests_user_id_users'), 'user_update_requests', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_update_requests_moderator_id_users'), 'user_update_requests', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_update_request_moderator_id_users'), 'user_update_requests', 'users', ['moderator_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_update_request_user_id_users'), 'user_update_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_club_update_requests_club_id_clubs'), 'club_update_requests', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_requests_moderator_id_users'), 'club_update_requests', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_update_requests_requestor_id_users'), 'club_update_requests', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_update_request_requestor_id_users'), 'club_update_requests', 'users', ['requestor_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_update_request_moderator_id_users'), 'club_update_requests', 'users', ['moderator_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_update_request_club_id_clubs'), 'club_update_requests', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_club_activity_update_requests_moderator_id_users'), 'club_activity_update_requests', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_requests_club_activity_id_club_activities'), 'club_activity_update_requests', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_update_requests_requestor_id_users'), 'club_activity_update_requests', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_update_request_requestor_id_users'), 'club_activity_update_requests', 'users', ['requestor_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_activity_update_request_moderator_id_users'), 'club_activity_update_requests', 'users', ['moderator_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_activity_update_request_club_activity_id_club_a_c5cc'), 'club_activity_update_requests', 'club_activities', ['club_activity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_club_activity_participants_club_activity_id_club_activities'), 'club_activity_participants', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_participants_user_id_users'), 'club_activity_participants', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_participators_club_activity_id_club_activities'), 'club_activity_participants', 'club_activities', ['club_activity_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_activity_participators_user_id_users'), 'club_activity_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_club_activity_create_requests_moderator_id_users'), 'club_activity_create_requests', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_requests_club_id_clubs'), 'club_activity_create_requests', schema='app', type_='foreignkey')
    op.drop_constraint(op.f('fk_club_activity_create_requests_requestor_id_users'), 'club_activity_create_requests', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('fk_club_activity_create_request_moderator_id_users'), 'club_activity_create_requests', 'users', ['moderator_id'], ['id'])
    op.create_foreign_key(op.f('fk_club_activity_create_request_club_id_clubs'), 'club_activity_create_requests', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_club_activity_create_request_requestor_id_users'), 'club_activity_create_requests', 'users', ['requestor_id'], ['id'])
    # ### end Alembic commands ###
