"""empty message

Revision ID: 8cb927d591fd
Revises: 56129826055b
Create Date: 2026-04-25 11:15:55.775062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb927d591fd'
down_revision: Union[str, Sequence[str], None] = '56129826055b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('ban', 'user', 'moderator', 'scf', 'admin', 'dev', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ban', 'user', 'moderator', 'scf', 'admin', 'dev', name='roleenum'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
