"""add picture_urls to Activity

Revision ID: 957e80cfc5c6
Revises: 40a7ec6abc1a
Create Date: 2026-04-06 00:13:00.436349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957e80cfc5c6'
down_revision: Union[str, Sequence[str], None] = '40a7ec6abc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_urls', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('picture_urls')

    # ### end Alembic commands ###
