"""empty message

Revision ID: 980bd7ea8cc3
Revises: b4b727525788
Create Date: 2026-05-02 00:07:46.806427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980bd7ea8cc3'
down_revision: Union[str, Sequence[str], None] = 'b4b727525788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_update_requests_club_id'), table_name='club_update_requests')
    op.drop_index(op.f('ix_club_update_requests_requester_id'), table_name='club_update_requests')
    op.drop_table('club_update_requests')
    op.drop_index(op.f('ix_only_one_current'), table_name='academic_term', postgresql_where='(is_current IS TRUE)')
    op.create_index('ix_only_one_current', 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.drop_index(op.f('ix_unique_active_club_name'), table_name='clubs', postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.create_index('ix_unique_active_club_name', 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.execute(
        "ALTER TABLE user_update_request "
        "ALTER COLUMN moderate_status "
        "TYPE moderatestatusenum "
        "USING moderate_status::text::moderatestatusenum"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE user_update_request "
        "ALTER COLUMN moderate_status "
        "TYPE moderatestatusenum "
        "USING moderate_status::text::moderatestatusenum"
    )
    op.drop_index('ix_unique_active_club_name', table_name='clubs')
    op.create_index(op.f('ix_unique_active_club_name'), 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.drop_index('ix_only_one_current', table_name='academic_term')
    op.create_index(op.f('ix_only_one_current'), 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.create_table('club_update_requests',
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('logo_uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('audit_status', postgresql.ENUM('pending', 'approved', 'rejected', name='auditstatusenum'), autoincrement=False, nullable=False),
    sa.Column('auditor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], name=op.f('fk_club_update_requests_auditor_id_users')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_update_requests_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_club_update_requests_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_update_requests'))
    )
    op.create_index(op.f('ix_club_update_requests_requester_id'), 'club_update_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_club_update_requests_club_id'), 'club_update_requests', ['club_id'], unique=False)
    # ### end Alembic commands ###
