"""empty message

Revision ID: 9ec6552e0335
Revises: 6aa866f8a18c
Create Date: 2026-04-07 15:29:40.011171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec6552e0335'
down_revision: Union[str, Sequence[str], None] = '6aa866f8a18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_club_gen_act_records_academic_term_id'), type_='foreignkey')
        batch_op.drop_column('academic_term_id')

    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_term_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_club_gen_act_records_academic_term_id', 'academic_term', ['academic_term_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_club_gen_act_records_academic_term_id', type_='foreignkey')
        batch_op.drop_column('academic_term_id')

    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_term_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_club_gen_act_records_academic_term_id'), 'academic_term', ['academic_term_id'], ['id'])

    # ### end Alembic commands ###
