"""empty message

Revision ID: b244353b0a9d
Revises: 9ec6552e0335
Create Date: 2026-04-07 15:32:15.081841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b244353b0a9d'
down_revision: Union[str, Sequence[str], None] = '9ec6552e0335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('academic_term_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.alter_column('academic_term_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.alter_column('academic_term_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('academic_term_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
