"""empty message

Revision ID: b4b727525788
Revises: 2d19f795b866
Create Date: 2026-04-29 20:24:10.852753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4b727525788'
down_revision: Union[str, Sequence[str], None] = '2d19f795b866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_activity_create_request',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', sa.Enum('pending', 'approved', 'rejected', name='moderatestatusenum'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_activity_create_request_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_club_activity_create_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], name=op.f('fk_club_activity_create_request_requestor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_activity_create_request'))
    )
    op.create_table('club_activity_update_request',
    sa.Column('club_activity_id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('picture_urls', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', sa.Enum('pending', 'approved', 'rejected', name='moderatestatusenum'), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_activity_id'], ['activities.id'], name=op.f('fk_club_activity_update_request_club_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_club_activity_update_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], name=op.f('fk_club_activity_update_request_requestor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_activity_update_request'))
    )
    op.create_index(
        'ix_only_one_current',
        'academic_term',
        ['is_current'],
        unique=True,
        sqlite_where=sa.text('is_current IS TRUE'),
        postgresql_where=sa.text('is_current IS TRUE'),
    )
    op.drop_index(op.f('ix_unique_active_club_name'), table_name='clubs', postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.create_index(
        'ix_unique_active_club_name',
        'clubs',
        ['name'],
        unique=True,
        sqlite_where=sa.text("status != 'archived'"),
        postgresql_where=sa.text("status != 'archived'")
    )
    op.alter_column('user_update_request', 'moderate_status',
                    existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='moderatestateenum'),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_update_request', 'moderate_status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='moderatestatusenum'),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='moderatestateenum'),
               existing_nullable=False)
    op.drop_index('ix_unique_active_club_name', table_name='clubs')
    op.create_index(op.f('ix_unique_active_club_name'), 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.drop_index('ix_only_one_current', table_name='academic_term')
    op.drop_table('club_activity_update_request')
    op.drop_table('club_activity_create_request')
    # ### end Alembic commands ###
