"""empty message

Revision ID: b6da8b660b54
Revises: d993e652eac6
Create Date: 2026-04-11 15:14:52.042491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

import app.utils.custom_types

# revision identifiers, used by Alembic.
revision: str = 'b6da8b660b54'
down_revision: Union[str, Sequence[str], None] = 'd993e652eac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star_level_applications',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('contest_attachment', app.utils.custom_types.HttpUrlType(), nullable=True),
    sa.Column('requested_contest_score', sa.Integer(), nullable=True),
    sa.Column('final_contest_score', sa.Integer(), nullable=True),
    sa.Column('uniqueness_statement', sa.Text(), nullable=True),
    sa.Column('uniqueness_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_score', sa.Integer(), nullable=True),
    sa.Column('approved_level', sa.Enum('none', 'one_star', 'two_star', 'three_star', 'four_star', 'five_star', 'honorary', name='clubstarlevelenum'), nullable=True),
    #sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('audit_status', sa.Enum('pending', 'approved', 'rejected', name='auditstatusenum'), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], name=op.f('fk_star_level_applications_academic_term_id_academic_term')),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], name=op.f('fk_star_level_applications_auditor_id_users')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_star_level_applications_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_star_level_applications')),
    #sa.UniqueConstraint('club_id', 'academic_term_id', name=op.f('uq_star_level_applications_club_id_academic_term_id'))
    )

    #with op.batch_alter_table('academic_term', schema=None) as batch_op:
    #    batch_op.create_unique_constraint(batch_op.f('uq_academic_term_term_name'), ['term_name'])

    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auditor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_club_general_activity_records_auditor_id_users'), 'users', ['auditor_id'], ['id'])

    with op.batch_alter_table('star_level_applications', schema=None) as batch_op:
        batch_op.alter_column('academic_term_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        #batch_op.create_foreign_key(batch_op.f('fk_star_level_applications_academic_term_id_academic_term'), 'academic_term', ['academic_term_id'], ['id'])

    #with op.batch_alter_table('users', schema=None) as batch_op:
    #    batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('users', schema=None) as batch_op:
    #    batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('star_level_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_star_level_applications_academic_term_id_academic_term'), type_='foreignkey')
        batch_op.alter_column('academic_term_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        #batch_op.drop_constraint(batch_op.f('fk_club_general_activity_records_auditor_id_users'), type_='foreignkey')
        batch_op.drop_column('auditor_id')

    #with op.batch_alter_table('academic_term', schema=None) as batch_op:
    #    batch_op.drop_constraint(batch_op.f('uq_academic_term_term_name'), type_='unique')
    op.drop_table('star_level_applications')
    # ### end Alembic commands ###
