"""empty message

Revision ID: cb0d6d975d27
Revises: b244353b0a9d
Create Date: 2026-04-07 18:48:42.883933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0d6d975d27'
down_revision: Union[str, Sequence[str], None] = 'b244353b0a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.alter_column('proof_files',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.alter_column('proof_files',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
