"""empty message

Revision ID: d1549c8fd5a9
Revises: d2236cbb2efe
Create Date: 2026-04-13 20:11:11.109643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.custom_types


# revision identifiers, used by Alembic.
revision: str = 'd1549c8fd5a9'
down_revision: Union[str, Sequence[str], None] = 'd2236cbb2efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_update_requests',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_uri', app.utils.custom_types.HttpUrlType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_status', sa.Enum('pending', 'approved', 'rejected', name='auditstatusenum'), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], name=op.f('fk_club_update_requests_auditor_id_users')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_update_requests_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_club_update_requests_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_update_requests'))
    )
    with op.batch_alter_table('club_update_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_update_requests_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_update_requests_requester_id'), ['requester_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_update_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_update_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_club_update_requests_club_id'))

    op.drop_table('club_update_requests')
    # ### end Alembic commands ###
