"""empty message

Revision ID: d2236cbb2efe
Revises: b6da8b660b54
Create Date: 2026-04-11 15:38:15.392335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2236cbb2efe'
down_revision: Union[str, Sequence[str], None] = 'b6da8b660b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('star_level_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_star_level_applications_club_id_academic_term_id'), ['club_id', 'academic_term_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('star_level_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_star_level_applications_club_id_academic_term_id'), type_='unique')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
