"""empty message

Revision ID: d650d54480d8
Revises: 7a501320a288
Create Date: 2026-04-05 10:17:47.053278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd650d54480d8'
down_revision: Union[str, Sequence[str], None] = '7a501320a288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    if op.get_bind().dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_participators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'activity_id')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index('ix_clubs_description_trgm', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'}, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
        batch_op.create_index('ix_clubs_name_trgm', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'}, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
        batch_op.create_index('ix_clubs_summary_trgm', ['summary'], unique=False, postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'}, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index('ix_clubs_summary_trgm', postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'}, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
        batch_op.drop_index('ix_clubs_name_trgm', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'}, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
        batch_op.drop_index('ix_clubs_description_trgm', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'}, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')

    op.drop_table('activity_participators')
    # ### end Alembic commands ###
