"""empty message

Revision ID: e4e4483e127f
Revises: c6ca48c7043a
Create Date: 2026-04-06 21:09:48.589586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e4483e127f'
down_revision: Union[str, Sequence[str], None] = 'c6ca48c7043a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_conditions',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_activities',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('school', 'large', 'sua', name='generalactivitylevelenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_activities_name'), ['name'], unique=False)

    op.create_table('club_general_activity_records',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('participation_type', sa.Enum('participate_only', 'organize', name='participationtypeenum'), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('audit_status', sa.Enum('pending', 'approved', 'rejected', name='auditstatusenum'), nullable=False),
    sa.Column('proof_files', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['general_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_general_activity_records_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_general_activity_records_club_id'), ['club_id'], unique=False)
        batch_op.create_index('ix_unique_club_activity_record', ['club_id', 'activity_id'], unique=True)

    op.create_table('record_condition_details',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('is_met', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['activity_conditions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['club_general_activity_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_condition_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_condition_details_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_condition_details_record_id'), ['record_id'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=False))

    with op.batch_alter_table('record_condition_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_condition_details_record_id'))
        batch_op.drop_index(batch_op.f('ix_record_condition_details_condition_id'))

    op.drop_table('record_condition_details')
    with op.batch_alter_table('club_general_activity_records', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_club_activity_record')
        batch_op.drop_index(batch_op.f('ix_club_general_activity_records_club_id'))
        batch_op.drop_index(batch_op.f('ix_club_general_activity_records_activity_id'))

    op.drop_table('club_general_activity_records')
    with op.batch_alter_table('general_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_activities_name'))

    op.drop_table('general_activities')
    op.drop_table('activity_conditions')
    # ### end Alembic commands ###
