"""empty message

Revision ID: e6af6f80ef64
Revises: 957768f3c0e7
Create Date: 2026-03-25 21:19:27.096338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6af6f80ef64'
down_revision: Union[str, Sequence[str], None] = '957768f3c0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clubs_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_uri',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_users_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.alter_column('avatar_uri',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_id'), ['id'], unique=False)

    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
