"""empty message

Revision ID: f3372962ae97
Revises:
Create Date: 2026-04-04 14:41:57.336865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3372962ae97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('unreviewed', 'normal', 'archived', name='clubstatusenum'), nullable=False),
    sa.Column('star_level', sa.Enum('none', 'one_star', 'two_star', 'three_star', 'four_star', 'five_star', 'honorary', name='clubstarlevelenum'), nullable=False),
    sa.Column('category', sa.Enum('sports', 'humanity', 'arts', 'science', 'charity', 'business', 'campus', 'other', name='clubcategoryenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_name'), ['name'], unique=False)
        batch_op.create_index('ix_unique_active_club_name', ['name'], unique=True, postgresql_where=sa.text("status != 'archived'"), sqlite_where=sa.text("status != 'archived'"))

    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_uri', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('real_name', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ban', 'user', 'union_of_associations', 'admin', 'dev', name='roleenum'), nullable=False),
    sa.Column('wecom_userid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wecom_userid'), ['wecom_userid'], unique=True)

    op.create_table('club_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('membership', sa.Enum('none', 'pending', 'member', 'president', 'vice', name='clubmembershipenum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uix_club_id_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_members')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wecom_userid'))
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_active_club_name', postgresql_where=sa.text("status != 'archived'"), sqlite_where=sa.text("status != 'archived'"))
        batch_op.drop_index(batch_op.f('ix_clubs_name'))

    op.drop_table('clubs')
    # ### end Alembic commands ###
