"""empty message

Revision ID: fc9178f84916
Revises: 572cc8a731c5
Create Date: 2026-05-02 09:53:47.096186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc9178f84916'
down_revision: Union[str, Sequence[str], None] = '572cc8a731c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_update_request',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_uri', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moderate_status', postgresql.ENUM('pending', 'approved', 'rejected', name='moderatestatusenum', create_type=False), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('moderate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_update_request_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_club_update_request_moderator_id_users')),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], name=op.f('fk_club_update_request_requestor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_update_request'))
    )
    op.drop_index(op.f('ix_only_one_current'), table_name='academic_term', postgresql_where='(is_current IS TRUE)')
    op.create_index('ix_only_one_current', 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.drop_index(op.f('ix_unique_active_club_name'), table_name='clubs', postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.create_index('ix_unique_active_club_name', 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_active_club_name', table_name='clubs')
    op.create_index(op.f('ix_unique_active_club_name'), 'clubs', ['name'], unique=True, postgresql_where="(status <> 'archived'::clubstatusenum)")
    op.drop_index('ix_only_one_current', table_name='academic_term')
    op.create_index(op.f('ix_only_one_current'), 'academic_term', ['is_current'], unique=True, postgresql_where='(is_current IS TRUE)')
    op.drop_table('club_update_request')
    # ### end Alembic commands ###
