name: Sync from Gitee
on:
  repository_dispatch:
    types: [gitee_push_event]
  workflow_dispatch:

permissions:
  contents: write    # 允许读取和写入代码库内容（git push 必需）
  actions: write     # 允许对 GitHub Actions 的写权限

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Repository from Gitee
        run: |
          git clone --mirror https://oauth2:${{ secrets.GITEE_PAT }}@gitee.com/bjbnds/BNDSphere.git repo-mirror
          cd repo-mirror
          git remote set-url --push origin https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push --mirror