from typing import Final

USER_MAX_USERNAME_LENGTH: Final[int] = 32
USER_MAX_EMAIL_LENGTH: Final[int] = 64
USER_MAX_DESCRIPTION_LENGTH: Final[int] = 400

CLUB_MAX_NAME_LENGTH: Final[int] = 128
CLUB_MAX_DESCRIPTION_LENGTH: Final[int] = 400
CLUB_MAX_SUMMARY_LENGTH: Final[int] = 50

TAG_MAX_NAME_LENGTH: Final[int] = 50

ACTIVITY_MAX_NAME_LENGTH: Final[int] = 64
ACTIVITY_MAX_DESCRIPTION_LENGTH: Final[int] = 400
ACTIVITY_MAX_LOCATION_LENGTH: Final[int] = 200

ACADEMIC_TERM_MAX_LENGTH: Final[int] = 50
